### ISSUE TITLE
how to balance the training data

### ISSUE THREAD

**Issue by Sisi0518** [qinenergy/webvision-2.0-benchmarks#2]
Does the comments "Due to the class imbalance in WebVision, we duplicated the file items in train.txt such that different classes have equal number of training samples." in the Readme mean that every class is up-sampled to the same number as the maximum number of classes, and the number of items of each class in the trianlist.txt is the same ?

**Comment by qinenergy** [comment]
Yes, we duplicated the items in trainlist.txt so that each class has the same number of items as the largest class has.

**Comment by qinenergy** [comment]
Check utils/upsample.py for an example.
