### ISSUE TITLE
Note that one epoch is defined as an iteration over 1280000 images

### ISSUE THREAD

**Issue by hectorgui** [qinenergy/webvision-2.0-benchmarks#4]
1280000 is for imagenet，your model should be trained on webvision2.0, so it should be 16M image one epoch?

**Comment by qinenergy** [comment]
Yes, it's 'Imagenet Epoch'. We are just using it as a count on number of iterations. 

ReadMe Updated for clarification.

**Comment by hectorgui** [comment]
3ks, no other problem.
btw, what is the type of your GPU， i guess it will be used several weeks or months to get the results? :)

**Comment by qinenergy** [comment]
V100s :joy:
