### ISSUE TITLE
validation on val set but get acc = 0

### ISSUE THREAD

**Issue by FCInter** [qinenergy/webvision-2.0-benchmarks#5]
Thank you for sharing the great code and ckpt files.

I download the ckpt files and code files, then run the following command:

`python3 ./imagenet-resnet.py --data ../data/ -d 50 --mode resnet --eval --load train_log/imagenet-resnet-d50-webvision2018-200epochs/model-1055000`

The reported error rate is 1.0, which means the accuracy is 0.

The only change I made to the settings is, I set the `data` argument to the local dataset directory. In `data`, I downloaded the webvision validation set from this [url](https://data.vision.ee.ethz.ch/cvl/webvision//download.html). I downloaded the `Validation Images Resized (834 MB) (md5sum)`, which is the so-called `Resized Images (small version)`.

There is no other change.

What's wrong with my test?

Thank you!

**Comment by qinenergy** [comment]
Hi,
The repository was trained on the 2.0 dataset which contains 5000 classes. The val dataset you used is from the 1.0 dataset which has 1000 classes. The label mapping is also different in the first 1000 classes. Thus leading to 0% accuracy.

This is the correct one (also resized) used in the 2.0 dataset:
https://data.vision.ee.ethz.ch/cvl/webvision2018/val_images_resized.tar

Hope this helps.
Best regards,
Qin

**Comment by FCInter** [comment]
Thx. It's solved.
